// SPDX-License-Identifier: GPL-3.0-only
//! `/settings` — the daemon's stored preferences.
//!
//! One value apiece: read it, write it, occasionally preview it. What lives
//! here is decided by subject, not by scope. The `settings` *scope* guards far
//! more than this — [`super::backends`], [`super::pipeline`] and
//! [`super::registry`] all sit behind it — and conflating the two is what once
//! filed a live GPU probe and a model catalog under "settings". A reader who
//! sees `/settings/` in a path should be able to conclude "this is a stored
//! preference" and be right every time; `url_surface_contract` holds that.
//!
//! Neighbours that are *about* settings without being one: [`super::gpu_info`]
//! probes hardware, [`super::models`] reads a catalog, [`super::update`]
//! reports and triggers self-update. The preferences governing that last one —
//! `update_check_enabled`, `update_beta_optin` — are settings, and are here.
//!
//! The handlers are generated by the macros in [`super::macros`]; the path
//! lives in the macro call and nowhere else.

pub(crate) mod audio_theme;
pub(crate) mod custom_models_dir;
pub(crate) mod language;
pub(crate) mod notification_method;
pub(crate) mod preview_typing;
pub(crate) mod recording_stop_mode;
pub(crate) mod update_beta_optin;
pub(crate) mod update_check_enabled;
pub(crate) mod volume;
pub(crate) mod write_method;

use crate::daemon::http::state::AppState;
use utoipa_axum::router::OpenApiRouter;
use utoipa_axum::routes;

/// Every `/settings` route.
///
/// No path appears here: `routes!` reads each one off the handler's
/// `#[utoipa::path]`, which is also what the `OpenAPI` document is generated
/// from. Handlers sharing a path are registered together, which is what makes
/// them one path item with several methods.
pub(crate) fn routes() -> OpenApiRouter<AppState> {
    OpenApiRouter::new()
        .routes(routes!(
            audio_theme::get_audio_theme,
            audio_theme::set_audio_theme
        ))
        .routes(routes!(audio_theme::test_audio_theme))
        .routes(routes!(audio_theme::list_audio_themes))
        .routes(routes!(volume::get_volume, volume::set_volume))
        .routes(routes!(
            recording_stop_mode::get_recording_stop_mode,
            recording_stop_mode::set_recording_stop_mode
        ))
        .routes(routes!(
            write_method::get_write_method,
            write_method::set_write_method
        ))
        .routes(routes!(write_method::test_write_method))
        .routes(routes!(
            notification_method::get_notification_method,
            notification_method::set_notification_method
        ))
        .routes(routes!(
            preview_typing::get_preview_typing,
            preview_typing::set_preview_typing
        ))
        .routes(routes!(
            custom_models_dir::get_custom_models_dir,
            custom_models_dir::set_custom_models_dir
        ))
        .routes(routes!(
            update_check_enabled::get_update_check_enabled,
            update_check_enabled::set_update_check_enabled
        ))
        .routes(routes!(
            update_beta_optin::get_update_beta_optin,
            update_beta_optin::set_update_beta_optin
        ))
        .routes(routes!(
            language::get_language,
            language::set_language,
            language::clear_language
        ))
        .routes(routes!(language::list_languages))
}
