// SPDX-License-Identifier: GPL-3.0-only
//! `/context/...` — the named dictation contexts and which one is in force.
//!
//! Contract: `docs/protocol/endpoints/v1/context.md`.
//!
//! A context is what the user is dictating: a `prompt` for a model that follows
//! instructions, a `vocabulary` of terms for one that does not. The daemon owns
//! the set, one is active at a time, and a backend may be pointed at a different
//! one — see [`backend`].
//!
//! Hand-written rather than generated by the settings macros, for the same
//! reason the daemon's side is: those macros are for a path with one value and
//! no parameter, and every path here has an id in it.

pub(crate) mod backend;

use crate::daemon::client::internal::response::require_unit;
use crate::daemon::client::internal::session::with_settings_token;
use serde::Deserialize;
use super_stt_shared::daemon::http_client::HttpResult;
use super_stt_shared::daemon::http_client::transport;
use super_stt_shared::models::contexts::DictationContext;

/// Every context, and which one is in force.
#[derive(Debug, Clone, Default, Deserialize)]
pub struct ContextCatalog {
    /// The id of the context in force, or `None` when none is.
    #[serde(default)]
    pub active: Option<String>,
    /// In the order the user arranged them, which is the order to render.
    #[serde(default)]
    pub contexts: Vec<DictationContext>,
}

/// One context, as the daemon stored it.
#[derive(Debug, Clone, Deserialize)]
struct OneContext {
    context: DictationContext,
}

/// The active selection, as the daemon reports it after a write.
///
/// The object is not read here: `GET /context/list` already carries both the
/// list and the active id, and the page re-reads that after every write anyway
/// — the selection is the one change a *different* row also has to show. This
/// type exists so the write's answer is parsed rather than discarded, which is
/// what makes a `404` on an unknown id an error instead of a silent no-op.
#[derive(Debug, Clone, Default, Deserialize)]
pub struct ActiveContext {
    #[serde(default)]
    id: Option<String>,
}

/// `GET /context/list` — every context plus the active id.
pub async fn list_contexts() -> HttpResult<ContextCatalog> {
    with_settings_token(|socket, token| async move {
        transport::get_json::<ContextCatalog>(socket, &token, "/context/list").await
    })
    .await
}

/// `POST /context/{id}` — create or replace, answering with the context as
/// stored.
///
/// Reading the answer rather than echoing what was sent is the point: the
/// daemon drops blank vocabulary terms and trims the rest, so the version that
/// comes back is the one the list should show.
pub async fn set_context(context: DictationContext) -> HttpResult<DictationContext> {
    with_settings_token(move |socket, token| {
        let context = context.clone();
        async move {
            let path = format!("/context/{}", urlencoding::encode(&context.id));
            let body = serde_json::json!({
                "name": context.name,
                "prompt": context.prompt,
                "vocabulary": context.vocabulary,
            });
            transport::post_json::<OneContext>(socket, &token, &path, &body)
                .await
                .map(|answer| answer.context)
        }
    })
    .await
}

/// `DELETE /context/{id}`.
pub async fn delete_context(id: String) -> HttpResult<()> {
    with_settings_token(move |socket, token| {
        let id = id.clone();
        async move {
            let path = format!("/context/{}", urlencoding::encode(&id));
            let resp = transport::settings_delete(socket, &token, &path).await?;
            require_unit(resp, "delete_context")
        }
    })
    .await
}

/// `POST /context/active` — put a context in force, or (`None`) leave none
/// active. Answers with the id now in force.
pub async fn set_active_context(id: Option<String>) -> HttpResult<Option<String>> {
    with_settings_token(move |socket, token| {
        let id = id.clone();
        async move {
            let body = serde_json::json!({ "id": id });
            transport::post_json::<ActiveContext>(socket, &token, "/context/active", &body)
                .await
                .map(|answer| answer.id)
        }
    })
    .await
}
