// SPDX-License-Identifier: GPL-3.0-only
//! `/models` — the models the backend filling stage 1 serves.
//!
//! Selecting and loading one happens through `/pipeline/{stage}/model` (see
//! [`super::pipeline`]); this is only the flat catalog read that a picker fills
//! itself from. The full catalog with roles is [`super::backends`].
//!
//! Written out rather than generated by `settings_dispatch!`: that macro is
//! textually scoped to [`super::settings`], and this path is not under it.

use crate::daemon::http::internal::helpers::dispatch::{build_request, dispatch, narrowed};
use crate::daemon::http::state::AppState;
use axum::extract::State;
use axum::response::Response;

use crate::daemon::http::v1::wire::{FromDaemon, ModelList};
use crate::daemon::http::wire::{ErrorEnvelope, ReasonEnvelope};

#[utoipa::path(
    get,
    path = "/models",
    tag = "models",
    summary = "List the models the active backend can transcribe with",
    description = "Scoped to the backend currently filling stage 1 — only its models are \
switchable. Post-processor models are excluded, since selecting one as a \
transcription model would fail every recording; the full catalog with roles is at \
`GET /backends`.",
    security(("session_token" = ["settings"])),
    responses(
        (status = 200, description = "Done.", body = ModelList),
        (status = 401, description = "Token unknown, expired, or its binary changed.",
         body = ReasonEnvelope),
        (status = 403, description = "The token lacks the `settings` scope.",
         body = ErrorEnvelope),
        (status = 429, description = "Per-client rate limit hit; back off and retry.",
         body = ErrorEnvelope),
    ),
)]
pub(crate) async fn list_models(State(s): State<AppState>) -> Response {
    let resp = dispatch(&s.daemon, build_request("list_models", None)).await;
    narrowed(resp, ModelList::from_daemon)
}
