// SPDX-License-Identifier: GPL-3.0-only
pub(crate) mod active_device;
pub(crate) mod active_model;
pub(crate) mod allow_online_models;
pub(crate) mod audio_theme;
pub(crate) mod backends;
pub(crate) mod custom_models_dir;
pub(crate) mod preview_typing;
pub(crate) mod recording_stop_mode;
pub(crate) mod volume;
pub(crate) mod write_method;
